"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input";
import { useAuthStore } from "@/lib/auth/auth-store"; import { useTextos } from "@/lib/config/textos-provider";
import { cancelarMensagemProgramada, listarMensagensProgramadas } from "@/lib/suporte/api";
import type { MensagemProgramada, StatusMensagemProgramada } from "@/lib/suporte/types";
import { FormularioMensagemProgramada } from "./formulario-mensagem-programada";

export function PaginaMensagensProgramadas(){const t=useTextos().mensagensProgramadas;const gestor=useAuthStore((s)=>s.papel)!=="ATENDENTE";const cache=useQueryClient();
 const[novo,setNovo]=useState(false);const[edicao,setEdicao]=useState<MensagemProgramada|null>(null);const[inicio,setInicio]=useState("");const[fim,setFim]=useState("");const[status,setStatus]=useState<StatusMensagemProgramada|"">("");const[pagina,setPagina]=useState(0);
 const q=useQuery({queryKey:["mensagens-programadas",inicio,fim,status,pagina],queryFn:()=>listarMensagensProgramadas({inicio:inicio?new Date(`${inicio}T00:00:00`).toISOString():undefined,fim:fim?new Date(`${fim}T23:59:59`).toISOString():undefined,status:status||undefined,pagina})});
 const cancelar=useMutation({mutationFn:cancelarMensagemProgramada,onSuccess:()=>cache.invalidateQueries({queryKey:["mensagens-programadas"]})});
 return <div className="space-y-5 p-6"><header className="flex justify-between"><div><h1 className="text-xl font-semibold">{t.titulo}</h1><p className="text-sm text-muted-foreground">{t.descricao}</p></div><Button onClick={()=>setNovo(true)}>{t.nova}</Button></header>
 <div className="flex flex-wrap gap-3 rounded-lg border p-3"><label className="text-sm">{t.filtros.inicio}<Input type="date" value={inicio} onChange={(e)=>{setInicio(e.target.value);setPagina(0)}}/></label><label className="text-sm">{t.filtros.fim}<Input type="date" value={fim} onChange={(e)=>{setFim(e.target.value);setPagina(0)}}/></label><label className="text-sm">{t.filtros.status}<select className="ml-2 h-8 rounded-lg border bg-background px-2" value={status} onChange={(e)=>{setStatus(e.target.value as StatusMensagemProgramada|"");setPagina(0)}}><option value="">{t.filtros.todos}</option><option value="AGENDADA">{t.status.agendada}</option><option value="ENVIADA">{t.status.enviada}</option><option value="CANCELADA">{t.status.cancelada}</option></select></label></div>
 {q.isLoading?<p>{t.carregando}</p>:q.isError?<p className="text-destructive">{t.erro}</p>:!q.data?.mensagens.length?<p>{t.vazio}</p>:<div className="overflow-x-auto rounded-lg border"><table className="w-full text-sm"><thead className="bg-muted"><tr><th className="p-2 text-left">{t.colunas.data}</th><th className="p-2 text-left">{t.colunas.lead}</th>{gestor&&<th className="p-2 text-left">{t.colunas.atendente}</th>}<th className="p-2 text-left">{t.colunas.conteudo}</th><th className="p-2 text-left">{t.colunas.status}</th><th className="p-2 text-left">{t.colunas.acoes}</th></tr></thead><tbody>{q.data.mensagens.map((m)=><tr className="border-t" key={m.id}><td className="p-2">{new Date(m.dataEnvio).toLocaleString()}</td><td className="p-2">{m.leadNome}</td>{gestor&&<td className="p-2">{m.atendenteNome}</td>}<td className="p-2">{m.conteudo}</td><td className="p-2">{t.status[m.status.toLowerCase() as "agendada"|"enviada"|"cancelada"]}</td><td className="space-x-2 p-2">{m.status==="AGENDADA"&&<><Button size="sm" variant="outline" onClick={()=>setEdicao(m)}>{t.editar}</Button><Button size="sm" variant="ghost" onClick={()=>cancelar.mutate(m.id)}>{t.cancelar}</Button></>}</td></tr>)}</tbody></table></div>}
 <div className="flex justify-end gap-2"><Button variant="outline" disabled={!pagina} onClick={()=>setPagina((p)=>p-1)}>{t.paginacao.anterior}</Button><Button variant="outline" disabled={!q.data?.temMais} onClick={()=>setPagina((p)=>p+1)}>{t.paginacao.proxima}</Button></div>
 <FormularioMensagemProgramada aberto={novo} onFechar={()=>setNovo(false)}/>{edicao&&<FormularioMensagemProgramada aberto existente={edicao} onFechar={()=>setEdicao(null)}/>}</div>}
