import { z } from "zod";

/**
 * Espelha tema.json (backend/crm-app/src/main/resources/tema.json), gerado a partir de
 * design/TOKENS.md. Nenhum campo tem default aqui: se o backend não devolver um token, a falha deve
 * aparecer (schema inválido), não virar uma cor arbitrária escolhida em runtime.
 */
export const TemaSchema = z.object({
  corPrimaria: z.string(),
  corPrimariaHover: z.string(),
  corPrimariaSuave: z.string(),
  corPrimariaBorda: z.string(),
  corPrimariaTexto: z.string(),

  fundoApp: z.string(),
  fundoCanvas: z.string(),
  fundoSuperficie: z.string(),
  fundoSutil: z.string(),
  fundoSidebar: z.string(),
  fundoSidebarBloco: z.string(),

  textoForte: z.string(),
  textoPadrao: z.string(),
  textoSuave: z.string(),
  textoFraco: z.string(),
  textoSidebarTitulo: z.string(),
  textoSidebarSub: z.string(),
  textoSidebarItem: z.string(),
  sidebarItemTextoHover: z.string(),
  sidebarItemIconeAtivo: z.string(),
  sidebarItemOverlayHover: z.string(),
  sidebarItemOverlayAtivo: z.string(),
  sidebarItemOverlayAtivoHover: z.string(),
  sidebarItemAcentoAtivo: z.string(),
  marcaIconeGradienteInicio: z.string(),
  marcaIconeGradienteFim: z.string(),
  sidebarItemTextoPerigo: z.string(),
  sidebarItemOverlayPerigo: z.string(),

  borda: z.string(),
  bordaForte: z.string(),
  bordaSuave: z.string(),

  corSucesso: z.string(),
  corAtencao: z.string(),
  corAtencaoEscura: z.string(),
  corIa: z.string(),
  corInfo: z.string(),
  corDestaque2: z.string(),
  corDestaque3: z.string(),
  corErro: z.string(),
  corErroSuave: z.string(),

  fonteBase: z.string(),
  fonteMono: z.string(),

  textoXs: z.string(),
  textoSm: z.string(),
  textoBase: z.string(),
  textoMd: z.string(),
  textoLg: z.string(),
  textoXl: z.string(),
  texto2xl: z.string(),

  raioSm: z.string(),
  raioMd: z.string(),
  raioLg: z.string(),
  raioXl: z.string(),
  raioPill: z.string(),

  sombraSm: z.string(),
  sombraMd: z.string(),
  sombraLg: z.string(),
  sombraXl: z.string(),
  sombraPrimaria: z.string(),

  logoUrl: z.string().nullable(),
});

export type Tema = z.infer<typeof TemaSchema>;

/** Espelha textos.json — catálogo de strings de UI. Cresce conforme novas telas nascem. */
export const TextosSchema = z.object({
  app: z.object({
    nome: z.string(),
    marca: z.string(),
    subtitulo: z.string(),
  }),
  menu: z.object({
    grupoMenu: z.string(),
    grupoGestao: z.string(),
    itens: z.record(z.string(), z.string()),
  }),
  rodape: z.object({
    trocarConta: z.string(),
    sair: z.string(),
    presenca:z.object({rotulo:z.string(),online:z.string(),ausente:z.string(),offline:z.string()}),
  }),
  login: z.object({
    titulo: z.string(),
    subtitulo: z.string(),
    campoEmail: z.string(),
    campoSenha: z.string(),
    botaoEntrar: z.string(),
    entrando: z.string(),
    erroCredenciais: z.string(),
    erroGenerico: z.string(),
  }),
  estados: z.object({
    carregando: z.string(),
    vazio: z.string(),
    erroGenerico: z.string(),
    tentarNovamente: z.string(),
    emConstrucao: z.string(),
    sessaoExpirada: z.string(),
  }),
  atendimentos: z.object({
    visoes: z.object({
      ativos: z.string(),
      pendentes: z.string(),
      potenciais: z.string(),
      todos: z.string(),
    }),
    filtros: z.object({
      etapa: z.string(),
      status: z.string(),
      tag: z.string(),
      atendente: z.string(),
      busca: z.string(),
    }),
    cartao: z.object({
      semAtendente: z.string(),
      vazio: z.string(),
    }),
    cabecalho: z.object({
      atendidoPor: z.string(),
      semAtendente: z.string(),
      transferir: z.string(),
      finalizar: z.string(),
      buscar: z.string(),
    }),
    transferir: z.object({
      titulo: z.string(),
      descricao: z.string(),
      devolverParaIa: z.string(),
      assumirParaMim: z.string(),
      confirmar: z.string(),
      cancelar: z.string(),
      sucesso: z.string(),
      erro: z.string(),
    }),
    finalizar: z.object({
      titulo: z.string(),
      descricao: z.string(),
      confirmar: z.string(),
      cancelar: z.string(),
      sucesso: z.string(),
      erro: z.string(),
    }),
    mensagem: z.object({
      status: z.object({
        pendente: z.string(),
        enviado: z.string(),
        entregue: z.string(),
        lido: z.string(),
        falhou: z.string(),
      }),
      reenviar: z.string(),
      carregarAnteriores: z.string(),
      carregandoAnteriores: z.string(),
    }),
    composer: z.object({
      placeholder: z.string(),
      enviar: z.string(),
      anexo: z.string(),
      anexoIndisponivel: z.string(),
      anexoSelecionar: z.string(),
      anexoRemover: z.string(),
      anexoEnviando: z.string(),
      anexoErro: z.string(),
      anexoLegendaPlaceholder: z.string(),
      anexoTipoNaoPermitido: z.string(),
      anexoExcedeuLimite: z.string(),
      emoji: z.string(),
      janelaFechadaTitulo: z.string(),
      janelaFechadaDescricao: z.string(),
      semTemplates: z.string(),
      agendar: z.string(),
      mensagensRapidas: z.string(),
    }),
    tempoReal: z.object({
      reconectando: z.string(),
      conversaEncerrada: z.string(),
    }),
    media: z.object({
      imagem: z.string(),
      audio: z.string(),
      documento: z.string(),
      baixar: z.string(),
    }),
    painel: z.object({
      titulo: z.string(),
      notasInternas: z.string(),
      secoes: z.object({
        resumo: z.string(),
        programadas: z.string(),
        lembretes: z.string(),
      }),
      vazioProgramadas: z.string(),
      vazioLembretes: z.string(),
    }),
  }),
  painelLead: z.object({
    titulo: z.string(),
    fechar: z.string(),
    indisponivel: z.string(),
    dados: z.object({
      telefone: z.string(),
      email: z.string(),
      cpf: z.string(),
      empresa: z.string(),
      localizacao: z.string(),
      canalOrigem: z.string(),
      naoInformado: z.string(),
    }),
    etapa: z.object({
      titulo: z.string(),
      posicao: z.string(),
      semEtapa: z.string(),
    }),
    contadores: z.object({
      atendimentos: z.string(),
      mensagens: z.string(),
    }),
    tags: z.object({
      titulo: z.string(),
      selecionar: z.string(),
      adicionar: z.string(),
      remover: z.string(),
      erroReversao: z.string(),
    }),
    resumoIa: z.object({
      titulo: z.string(),
      vazio: z.string(),
    }),
    edicao: z.object({
      notas: z.string(),
      notasPlaceholder: z.string(),
      camposCustomizados: z.string(),
      obrigatorio: z.string(),
      opcional: z.string(),
      salvar: z.string(),
      salvando: z.string(),
      salvo: z.string(),
      campoObrigatorio: z.string(),
      erroReversao: z.string(),
    }),
    timeline: z.object({
      titulo: z.string(),
      vazia: z.string(),
      carregarMais: z.string(),
      carregandoMais: z.string(),
      erro: z.string(),
      origens: z.object({
        sistema: z.string(),
        automacao: z.string(),
        usuario: z.string(),
      }),
    }),
    acoes: z.object({ lembrete: z.string(), mensagemProgramada: z.string() }),
  }),
  lembretes: z.object({
    titulo: z.string(), descricao: z.string(), novo: z.string(), carregando: z.string(),
    vazio: z.string(), erro: z.string(), automatico: z.string(), concluir: z.string(), remover: z.string(),
    status: z.object({ pendente: z.string(), concluido: z.string() }),
    filtros: z.object({ inicio: z.string(), fim: z.string(), status: z.string(), todos: z.string() }),
    semVinculo: z.string(),
    colunas: z.object({
      texto: z.string(),
      lead: z.string(),
      dataHora: z.string(),
      status: z.string(),
      atendente: z.string(),
      acoes: z.string(),
    }),
    paginacao: z.object({ anterior: z.string(), proxima: z.string() }),
    formulario: z.object({ titulo: z.string(), lead: z.string(), selecionarLead: z.string(), dataHora: z.string(), selecionarData: z.string(), hora: z.string(), minuto: z.string(), texto: z.string(), salvar: z.string(), cancelar: z.string(), erro: z.string() }),
  }),
  mensagensProgramadas: z.object({
    titulo:z.string(),descricao:z.string(),nova:z.string(),carregando:z.string(),vazio:z.string(),erro:z.string(),editar:z.string(),cancelar:z.string(),
    status:z.object({agendada:z.string(),enviada:z.string(),cancelada:z.string()}),
    filtros:z.object({inicio:z.string(),fim:z.string(),status:z.string(),todos:z.string()}),
    colunas: z.object({
      lead: z.string(),
      conteudo: z.string(),
      data: z.string(),
      status: z.string(),
      atendente: z.string(),
      acoes: z.string(),
    }),
    paginacao:z.object({anterior:z.string(),proxima:z.string()}),
    formulario:z.object({tituloCriar:z.string(),tituloEditar:z.string(),lead:z.string(),selecionarLead:z.string(),dataEnvio:z.string(),selecionarData:z.string(),hora:z.string(),minuto:z.string(),conteudo:z.string(),salvar:z.string(),cancelar:z.string(),erro:z.string()}),
  }),
  mensagensRapidas: z.object({
    titulo: z.string(),
    descricao: z.string(),
    nova: z.string(),
    carregando: z.string(),
    vazio: z.string(),
    erro: z.string(),
    editar: z.string(),
    remover: z.string(),
    dica: z.string(),
    formulario: z.object({
      criarTitulo: z.string(),
      editarTitulo: z.string(),
      chave: z.string(),
      conteudo: z.string(),
      salvar: z.string(),
      cancelar: z.string(),
      erro: z.string(),
    }),
  }),
  equipe: z.object({
    titulo: z.string(),
    descricao: z.string(),
    novo: z.string(),
    carregando: z.string(),
    erro: z.string(),
    inativo: z.string(),
    editar: z.string(),
    desativar: z.string(),
    colunas: z.object({
      usuario: z.string(),
      funcao: z.string(),
      presenca: z.string(),
      avaliacao: z.string(),
      atendimentos: z.string(),
      vendas: z.string(),
      acoes: z.string(),
    }),
    dashboard: z.object({
      equipeLabel: z.string(),
      onlineLabel: z.string(),
      avaliacaoMedia: z.string(),
      rankingAvaliacao: z.string(),
      rankingVendas: z.string(),
    }),
    grade: z.object({ titulo: z.string() }),
    papeis: z.object({ atendente: z.string(), subgestor: z.string() }),
    presenca: z.object({ online: z.string(), ausente: z.string(), offline: z.string() }),
    avaliacoes: z.object({ media: z.string(), total: z.string(), semDados: z.string() }),
    formulario: z.object({
      criarTitulo: z.string(),
      editarTitulo: z.string(),
      nome: z.string(),
      email: z.string(),
      senha: z.string(),
      papel: z.string(),
      atendente: z.string(),
      subgestor: z.string(),
      salvar: z.string(),
      cancelar: z.string(),
      erro: z.string(),
    }),
  }),
  dashboard: z.object({
    titulo: z.string(), descricao: z.string(), carregando: z.string(), erro: z.string(), semDado: z.string(),
    abas: z.object({ rotulo: z.string(), visaoGeral: z.string(), operacional: z.string(), comercial: z.string(), iaAutomacao: z.string(), depois: z.string() }),
    filtros: z.object({ rotulo: z.string(), ano: z.string(), meses: z.string(), originacao: z.string(), de: z.string(), ate: z.string(), limpar: z.string(), selecioneMes: z.string(), origemCompleta: z.string() }),
    meses: z.array(z.string()).length(12),
    kpis: z.object({ rotulo: z.string(), atendimentos: z.string(), atendimentosApoio: z.string(), conversao: z.string(), conversaoApoio: z.string(), tempoMedio: z.string(), tempoMedioApoio: z.string(), vendas: z.string(), vendasApoio: z.string(), csat: z.string(), csatApoio: z.string(), resolucaoIa: z.string(), resolucaoIaApoio: z.string(), periodoAnterior: z.string() }),
    secoes: z.object({ ranking: z.string(), funil: z.string(), horarioPico: z.string() }),
    ranking: z.object({ vazio: z.string(), semResponsavelSingular: z.string(), semResponsavelPlural: z.string() }),
    funil: z.object({ vazio: z.string() }),
    horario: z.object({ vazio: z.string(), hora: z.string() }),
    tempo: z.object({ minutos: z.string(), horasMinutos: z.string() }),
  }),
  agenda: z.object({
    titulo: z.string(),
    descricao: z.string(),
    vazia: z.string(),
    carregando: z.string(),
    erro: z.string(),
    semResponsavel: z.string(),
    contador: z.string(),
    colunas: z.object({
      lead: z.string(),
      telefone: z.string(),
      cidade: z.string(),
      etapa: z.string(),
      tags: z.string(),
      responsavel: z.string(),
      ultimoContato: z.string(),
    }),
    status: z.object({ ia: z.string(), emAtendimento: z.string(), finalizado: z.string() }),
    filtros: z.object({
      titulo: z.string(),
      busca: z.string(),
      buscaPlaceholder: z.string(),
      avancados: z.string(),
      etapa: z.string(),
      atendente: z.string(),
      cidade: z.string(),
      tag: z.string(),
      adicionar: z.string(),
      campo: z.string(),
      operador: z.string(),
      valor: z.string(),
      valorInicial: z.string(),
      valorFinal: z.string(),
      selecionarCampo: z.string(),
      selecionarOperador: z.string(),
      selecionarValor: z.string(),
      limparTudo: z.string(),
      carregandoCampos: z.string(),
      erroCampos: z.string(),
      operadores: z.object({
        igual: z.string(),
        diferente: z.string(),
        contem: z.string(),
        comecaCom: z.string(),
        maiorQue: z.string(),
        menorQue: z.string(),
        entre: z.string(),
        em: z.string(),
        preenchido: z.string(),
        vazio: z.string(),
      }),
    }),
    paginacao: z.object({ anterior: z.string(), proxima: z.string() }),
  }),
  tags: z.object({
    titulo: z.string(),
    descricao: z.string(),
    busca: z.string(),
    nova: z.string(),
    carregando: z.string(),
    vazio: z.string(),
    semResultados: z.string(),
    erro: z.string(),
    editar: z.string(),
    remover: z.string(),
    dashboard: z.object({
      totalTags: z.string(),
      tagMaisUsada: z.string(),
      leadsVinculados: z.string(),
      leadsTagueados: z.string(),
      leadsDeTotal: z.string(),
      semDados: z.string(),
    }),
    grade: z.object({
      titulo: z.string(),
      leadsEPercentual: z.string(),
      previa: z.string(),
    }),
    formulario: z.object({
      criarTitulo: z.string(),
      editarTitulo: z.string(),
      nome: z.string(),
      nomePlaceholder: z.string(),
      cor: z.string(),
      icone: z.string(),
      salvar: z.string(),
      cancelar: z.string(),
      erro: z.string(),
    }),
  }),
  automacao: z.object({
    titulo: z.string(),
    descricao: z.string(),
    carregando: z.string(),
    vazio: z.string(),
    erro: z.string(),
    erroSalvar: z.string(),
    erroFaixa: z.string(),
    faixaLabel: z.string(),
    ativado: z.string(),
    desativado: z.string(),
    salvar: z.string(),
    salvando: z.string(),
    telemetria: z.object({
      mensagensEnviadas: z.string(),
      clientesTransferidos: z.string(),
      conexaoAutomacao: z.string(),
      statusDoCrm: z.string(),
      conectado: z.string(),
      desconectado: z.string(),
      online: z.string(),
      offline: z.string(),
      erro: z.string(),
    }),
  }),
});

export type Textos = z.infer<typeof TextosSchema>;
