/*
 * GERADO a partir da secao "campanhas" de textos.json (E220). Nao editar a mao: altere textos.json e
 * regenere o arquivo (o teste de schema.test.ts confere que os dois continuam alinhados).
 *
 * Todos os campos tem default: frontend e backend tem rollout independente, e um backend anterior a
 * campanhas serve textos.json sem esta secao (mesma regra de schema-gestao.ts).
 */
import { z } from "zod";

export const CampanhasTextosSchema = z.object({
  titulo: z.string().default("Campanhas"),
  descricao: z.string().default("Envie um template aprovado da Meta para muitos contatos da Agenda, em ondas, respeitando o limite diário."),
  novaCampanha: z.string().default("Nova campanha"),
  configuracao: z.string().default("Configurações"),
  voltar: z.string().default("Voltar para campanhas"),
  semAcessoTitulo: z.string().default("Sem acesso às campanhas"),
  semAcessoDescricao: z.string().default("Campanhas ficam disponíveis para gestor, subgestor e administrador."),
  indisponivelTitulo: z.string().default("Campanhas indisponíveis neste canal"),
  indisponivelDescricao: z.string().default("Campanhas em massa usam templates da Meta e só funcionam com o provedor oficial (Estrutural)."),
  somenteAdministrador: z.string().default("Somente o administrador pode fazer isto."),
  ajudaSomenteAdministrador: z.string().default("Peça a um administrador. Gestor e subgestor acompanham, mas não iniciam, pausam nem cancelam."),
  criarSomenteAdministrador: z.string().default("Só o administrador cria campanhas. Você acompanha as existentes e consulta as configurações."),
  erroCarregar: z.string().default("Não foi possível carregar as campanhas."),
  erroAcao: z.string().default("Não foi possível concluir a ação. Tente de novo."),
  indicadores: z.object({
    enviadasHoje: z.string().default("Enviadas hoje"),
    limiteDiario: z.string().default("Limite diário da instância"),
    deLimite: z.string().default("de {limite}"),
    metaInformado: z.string().default("Limite da Meta informado: {limite} contatos por 24h"),
    enviadas: z.string().default("Enviadas"),
    entregues: z.string().default("Entregues"),
    lidas: z.string().default("Lidas"),
    respostas: z.string().default("Respostas"),
    falhas: z.string().default("Falhas"),
    rotuloBarra: z.string().default("{enviadas} de {limite} mensagens do limite diário usadas hoje"),
  }).default({}),
  lista: z.object({
    titulo: z.string().default("Suas campanhas"),
    carregando: z.string().default("Carregando campanhas"),
    vazioTitulo: z.string().default("Nenhuma campanha ainda"),
    vazioDescricao: z.string().default("Crie a primeira campanha para avisar muitos contatos de uma vez, sem passar do limite diário."),
    vazioAcao: z.string().default("Criar a primeira campanha"),
    colunas: z.object({
      nome: z.string().default("Campanha"),
      template: z.string().default("Template"),
      status: z.string().default("Status"),
      progresso: z.string().default("Progresso"),
      enviadas: z.string().default("Enviadas / total"),
      limite: z.string().default("Limite diário"),
      inicio: z.string().default("Início"),
      acoes: z.string().default("Ações"),
    }).default({}),
    porDia: z.string().default("{limite}/dia"),
    naoIniciada: z.string().default("Não iniciada"),
    agendadaPara: z.string().default("Agendada para {data}"),
    abrir: z.string().default("Abrir"),
    continuarRascunho: z.string().default("Continuar rascunho"),
    progressoDe: z.string().default("{percentual}% concluído"),
    paginaAnterior: z.string().default("Anterior"),
    paginaSeguinte: z.string().default("Seguinte"),
    paginaDe: z.string().default("Página {pagina} de {total}"),
  }).default({}),
  status: z.object({
    RASCUNHO: z.string().default("Rascunho"),
    AGENDADA: z.string().default("Agendada"),
    EM_ANDAMENTO: z.string().default("Em andamento"),
    PAUSADA: z.string().default("Pausada"),
    CONCLUIDA: z.string().default("Concluída"),
    CANCELADA: z.string().default("Cancelada"),
    PAUSADA_AUTOMATICAMENTE: z.string().default("Pausada automaticamente"),
  }).default({}),
  statusDoDestinatario: z.object({
    PENDENTE: z.string().default("Na fila"),
    ENFILEIRADO: z.string().default("Enfileirado"),
    ENVIADO: z.string().default("Enviado"),
    ENTREGUE: z.string().default("Entregue"),
    LIDO: z.string().default("Lido"),
    FALHA: z.string().default("Falha"),
    IGNORADO: z.string().default("Ignorado"),
  }).default({}),
  motivos: z.object({
    TELEFONE_INVALIDO: z.string().default("Telefone inválido"),
    SEM_NOME_UTILIZAVEL: z.string().default("Sem nome utilizável"),
    OPT_OUT: z.string().default("Pediu para não receber"),
    JA_RECEBEU: z.string().default("Já recebeu esta campanha"),
    ATENDIMENTO_ATIVO: z.string().default("Em atendimento ativo"),
    RECEBEU_PROATIVA_RECENTE: z.string().default("Recebeu mensagem proativa recente"),
    COOLDOWN: z.string().default("Em período de espera entre mensagens proativas"),
    TETO_DIARIO_POR_LEAD: z.string().default("Já atingiu o teto diário de proativas"),
    TIPO_PROATIVO_DESLIGADO: z.string().default("Tipo de mensagem proativa desligado"),
    AUTOMACAO_PROATIVA_DESLIGADA: z.string().default("Automação proativa desligada"),
    OCORRENCIA_JA_REGISTRADA: z.string().default("Ocorrência já registrada"),
    LEAD_INDISPONIVEL: z.string().default("Contato indisponível"),
    ATENDIMENTO_ABERTO_NO_ENVIO: z.string().default("Abriu atendimento antes do envio"),
    OPT_OUT_NO_ENVIO: z.string().default("Pediu para não receber antes do envio"),
    ENVIO_NAO_CONFIRMADO: z.string().default("Envio sem confirmação do provedor"),
    FALHA_NO_PROVEDOR: z.string().default("Recusado pelo provedor"),
    ENFILEIRADO_SEM_CONFIRMACAO: z.string().default("Enfileirado sem confirmação"),
  }).default({}),
  acoes: z.object({
    pausar: z.string().default("Pausar"),
    retomar: z.string().default("Retomar"),
    cancelar: z.string().default("Cancelar campanha"),
    pausando: z.string().default("Pausando..."),
    retomando: z.string().default("Retomando..."),
    cancelando: z.string().default("Cancelando..."),
    cancelarTitulo: z.string().default("Cancelar esta campanha?"),
    cancelarDescricao: z.string().default("O que ainda está na fila nunca será enviado e a campanha não pode ser retomada. O que já foi enfileirado segue o fluxo normal de entrega."),
    cancelarConfirmar: z.string().default("Cancelar campanha"),
    manter: z.string().default("Manter campanha"),
    pausarAjuda: z.string().default("O envio para no próximo ciclo. Nada se perde e você pode retomar."),
    interruptorLigado: z.string().default("Envio ligado"),
    interruptorDesligado: z.string().default("Envio desligado"),
    interruptorAjuda: z.string().default("Desligar para o envio na hora, sem mudar o status. Religar continua de onde parou."),
  }).default({}),
  assistente: z.object({
    titulo: z.string().default("Nova campanha"),
    tituloEdicao: z.string().default("Continuar campanha"),
    passoDe: z.string().default("Passo {passo} de {total}"),
    passos: z.object({
      template: z.string().default("Template"),
      publico: z.string().default("Público"),
      ritmo: z.string().default("Ritmo e agenda"),
      revisao: z.string().default("Revisão"),
    }).default({}),
    rotuloProgresso: z.string().default("Progresso do assistente"),
    avancar: z.string().default("Avançar"),
    voltar: z.string().default("Voltar"),
    salvarRascunho: z.string().default("Salvar rascunho"),
    salvando: z.string().default("Salvando..."),
    rascunhoSalvo: z.string().default("Rascunho salvo"),
    erroSalvar: z.string().default("Não foi possível salvar o rascunho."),
    erroCarregarRascunho: z.string().default("Não foi possível abrir o rascunho."),
    sair: z.string().default("Sair do assistente"),
  }).default({}),
  passoTemplate: z.object({
    nome: z.string().default("Nome da campanha"),
    nomePlaceholder: z.string().default("Ex.: Retorno de orçamentos de outubro"),
    nomeAjuda: z.string().default("Só você e sua equipe veem o nome."),
    escolha: z.string().default("Escolha o template"),
    busca: z.string().default("Buscar template"),
    carregando: z.string().default("Carregando templates"),
    erro: z.string().default("Não foi possível carregar os templates da conta."),
    vazio: z.string().default("Nenhum template aprovado nesta conta."),
    vazioDescricao: z.string().default("Crie e aprove um template na tela de Templates do WhatsApp antes de montar uma campanha."),
    irParaTemplates: z.string().default("Ir para Templates"),
    semResultados: z.string().default("Nenhum template encontrado."),
    idioma: z.string().default("Idioma"),
    categoria: z.string().default("Categoria"),
    naoSuportado: z.string().default("Não suportado nesta versão"),
    restricoes: z.object({
      CATEGORIA_AUTENTICACAO: z.string().default("É de autenticação (código), não de campanha."),
      CABECALHO_DE_MIDIA: z.string().default("Tem mídia no cabeçalho."),
      CABECALHO_COM_VARIAVEL: z.string().default("Tem variável no cabeçalho."),
      BOTAO_COM_PARAMETRO: z.string().default("Tem botão com parâmetro."),
      OUTRO_COMPONENTE: z.string().default("Tem um componente ainda não suportado."),
    }).default({}),
    restricaoGenerica: z.string().default("Recurso ainda não suportado em campanhas."),
    previa: z.string().default("Como o contato vai ver"),
    contatoDeExemplo: z.string().default("Marina Souza"),
    empresaDeExemplo: z.string().default("Ateliê Souza"),
    localizacaoDeExemplo: z.string().default("Campinas"),
    variaveis: z.string().default("Variáveis do template"),
    semVariaveis: z.string().default("Este template não tem variáveis."),
    variavelRotulo: z.string().default("Variável {numero}"),
    campo: z.string().default("Preencher com"),
    reserva: z.string().default("Se o contato não tiver o dado"),
    reservaPlaceholder: z.string().default("Ex.: cliente"),
    reservaAjuda: z.string().default("Texto usado no lugar quando o campo está vazio."),
    campos: z.object({
      PRIMEIRO_NOME: z.string().default("Primeiro nome"),
      NOME_COMPLETO: z.string().default("Nome completo"),
      EMPRESA: z.string().default("Empresa"),
      LOCALIZACAO: z.string().default("Localização"),
    }).default({}),
    aviso: z.string().default("Campanhas enviam só o corpo do template. Cabeçalho com mídia ou variável e botões com parâmetro ainda não são suportados."),
    erroNome: z.string().default("Dê um nome à campanha."),
    erroTemplate: z.string().default("Escolha um template."),
    erroReserva: z.string().default("Informe o texto de reserva de cada variável."),
  }).default({}),
  passoPublico: z.object({
    titulo: z.string().default("Quem recebe"),
    agendaInteira: z.string().default("Toda a agenda"),
    agendaInteiraAjuda: z.string().default("Sem filtros: todos os contatos da Agenda que podem receber."),
    filtrosOpcionais: z.string().default("Filtros opcionais"),
    tags: z.string().default("Tags"),
    tagsPlaceholder: z.string().default("Qualquer tag"),
    etapa: z.string().default("Etapa"),
    etapaPlaceholder: z.string().default("Qualquer etapa"),
    cadastroDesde: z.string().default("Cadastrado desde"),
    cadastroAte: z.string().default("Cadastrado até"),
    nuncaConversou: z.string().default("Só quem nunca conversou"),
    busca: z.string().default("Nome ou telefone"),
    buscaPlaceholder: z.string().default("Buscar na agenda"),
    limparFiltros: z.string().default("Limpar filtros"),
    total: z.string().default("No filtro"),
    vaoReceber: z.string().default("Vão receber"),
    excluidos: z.string().default("Excluídos"),
    excluidosPorMotivo: z.string().default("Excluídos por motivo"),
    nenhumExcluido: z.string().default("Nenhum contato excluído."),
    verExcluidos: z.string().default("Ver lista"),
    excluidosTitulo: z.string().default("Excluídos: {motivo}"),
    excluidosDescricao: z.string().default("Até 200 contatos. Confira antes de iniciar."),
    excluidosVazio: z.string().default("Nenhum contato com este motivo."),
    carregando: z.string().default("Calculando o público"),
    erro: z.string().default("Não foi possível calcular o público."),
    publicoVazio: z.string().default("Nenhum contato vai receber com estes filtros. Ajuste os filtros para continuar."),
    fechar: z.string().default("Fechar"),
  }).default({}),
  passoRitmo: z.object({
    titulo: z.string().default("Ritmo e agenda"),
    limiteDiario: z.string().default("Mensagens por dia"),
    limiteAjuda: z.string().default("Nunca passa do teto da instância ({teto})."),
    limiteMeta: z.string().default("A Meta informou {meta} contatos por 24h."),
    limiteDeslizante: z.string().default("Limite diário (controle deslizante)"),
    atalhos: z.string().default("Atalhos"),
    atalhoTeto: z.string().default("Teto"),
    limiteInvalido: z.string().default("Informe um número entre 1 e {teto}."),
    limiteAcimaDoTeto: z.string().default("O limite não pode passar de {teto}, o teto diário da instância."),
    limiteAcimaDaMeta: z.string().default("Atenção: acima do limite informado da Meta ({meta}). A Meta pode barrar parte dos envios."),
    ritmo: z.string().default("Mensagens por minuto"),
    ritmoAjuda: z.string().default("Entre 1 e 600. Ritmo mais baixo parece mais natural para a Meta."),
    ritmoInvalido: z.string().default("Informe um número entre 1 e 600."),
    janela: z.string().default("Janela de envio"),
    janelaInicio: z.string().default("Das"),
    janelaFim: z.string().default("Até as"),
    janelaInvalida: z.string().default("O horário final precisa ser depois do inicial."),
    dias: z.string().default("Dias da semana"),
    diasAjuda: z.string().default("Escolha pelo menos um dia."),
    diasCurtos: z.object({
      "1": z.string().default("Seg"),
      "2": z.string().default("Ter"),
      "3": z.string().default("Qua"),
      "4": z.string().default("Qui"),
      "5": z.string().default("Sex"),
      "6": z.string().default("Sáb"),
      "7": z.string().default("Dom"),
    }).default({}),
    diasLongos: z.object({
      "1": z.string().default("segunda-feira"),
      "2": z.string().default("terça-feira"),
      "3": z.string().default("quarta-feira"),
      "4": z.string().default("quinta-feira"),
      "5": z.string().default("sexta-feira"),
      "6": z.string().default("sábado"),
      "7": z.string().default("domingo"),
    }).default({}),
    inicio: z.string().default("Começar"),
    iniciarAgora: z.string().default("Assim que eu iniciar"),
    agendar: z.string().default("Agendar"),
    agendadaPara: z.string().default("Data e hora de início"),
    agendaNoPassado: z.string().default("Escolha um horário no futuro."),
    rampa: z.string().default("Aumentar o limite aos poucos"),
    rampaAjuda: z.string().default("Comece com o limite acima e suba um pouco a cada dia até um teto. Bom para números novos."),
    rampaIncremento: z.string().default("Aumentar por dia"),
    rampaTeto: z.string().default("Até"),
    rampaInvalida: z.string().default("O teto da rampa precisa ser maior ou igual ao limite diário e não pode passar do teto da instância."),
    estimativa: z.string().default("Estimativa"),
    terminaEm: z.string().default("Termina em {data}"),
    diasNecessarios: z.string().default("{dias} dia(s) de envio"),
    estimativaIncompleta: z.string().default("A estimativa passa do horizonte calculado; o término real pode ser mais tarde."),
    calendario: z.string().default("Mensagens por dia"),
    calendarioRotulo: z.string().default("Calendário de envios por dia"),
    mensagensNoDia: z.string().default("{mensagens} msg"),
    carregando: z.string().default("Calculando a projeção"),
    erro: z.string().default("Não foi possível calcular a projeção."),
    semProjecao: z.string().default("Sem projeção: confira o limite, a janela e os dias."),
  }).default({}),
  passoRevisao: z.object({
    titulo: z.string().default("Revisão"),
    resumo: z.string().default("Resumo da campanha"),
    nome: z.string().default("Campanha"),
    template: z.string().default("Template"),
    mensagem: z.string().default("Mensagem"),
    publico: z.string().default("Público"),
    publicoValor: z.string().default("{receberao} vão receber de {total} no filtro"),
    filtros: z.string().default("Filtros"),
    semFiltros: z.string().default("Toda a agenda"),
    ritmo: z.string().default("Ritmo"),
    ritmoValor: z.string().default("{limite} por dia, {ritmo} por minuto"),
    janela: z.string().default("Janela"),
    janelaValor: z.string().default("{inicio} às {fim}, {dias}"),
    inicio: z.string().default("Início"),
    agora: z.string().default("Assim que iniciar"),
    termino: z.string().default("Término estimado"),
    rampa: z.string().default("Rampa"),
    rampaValor: z.string().default("+{incremento} por dia até {teto}"),
    teste: z.string().default("Envio de teste"),
    testeDescricao: z.string().default("Envie o template a um contato que já está na Agenda e que autorizou o teste. Não conta no limite diário."),
    testeTelefone: z.string().default("Telefone do contato de teste"),
    testePlaceholder: z.string().default("Ex.: 5511999990000"),
    testeAutorizou: z.string().default("O dono deste número autorizou o teste."),
    testeEnviar: z.string().default("Enviar teste"),
    testeEnviando: z.string().default("Enviando teste..."),
    testeEnviado: z.string().default("Teste enviado ao contato."),
    testeErro: z.string().default("Não foi possível enviar o teste."),
    consentimento: z.string().default("Confirmo que os contatos deste público aceitaram receber mensagens da empresa pelo WhatsApp e que o conteúdo respeita as políticas da Meta."),
    digiteTotal: z.string().default("Para iniciar, digite o número de destinatários: {receberao}"),
    digiteTotalRotulo: z.string().default("Número de destinatários"),
    digiteTotalPlaceholder: z.string().default("Digite {receberao}"),
    iniciar: z.string().default("Iniciar campanha"),
    agendarCampanha: z.string().default("Agendar campanha"),
    iniciando: z.string().default("Iniciando..."),
    erroIniciar: z.string().default("Não foi possível iniciar a campanha."),
    somenteAdministrador: z.string().default("Só o administrador pode iniciar campanhas."),
    pendencias: z.string().default("Falta resolver"),
    pendenciaConsentimento: z.string().default("Marque a confirmação de consentimento."),
    pendenciaTotal: z.string().default("Digite o número de destinatários."),
    pendenciaPublico: z.string().default("Nenhum contato vai receber."),
    pendenciaPermissao: z.string().default("Só o administrador pode iniciar."),
  }).default({}),
  detalhe: z.object({
    carregando: z.string().default("Carregando campanha"),
    erro: z.string().default("Não foi possível carregar a campanha."),
    template: z.string().default("Template: {nome}"),
    criadaEm: z.string().default("Criada em {data}"),
    iniciadaEm: z.string().default("Iniciada em {data}"),
    concluidaEm: z.string().default("Concluída em {data}"),
    atualizadoAutomaticamente: z.string().default("Atualiza sozinha enquanto a campanha envia."),
    abas: z.object({
      visaoGeral: z.string().default("Visão geral"),
      destinatarios: z.string().default("Destinatários"),
      conferencia: z.string().default("Conferência manual"),
    }).default({}),
    funil: z.object({
      titulo: z.string().default("Funil"),
      naFila: z.string().default("Na fila"),
      enviadas: z.string().default("Enviadas"),
      entregues: z.string().default("Entregues"),
      lidas: z.string().default("Lidas"),
      responderam: z.string().default("Responderam"),
      falhas: z.string().default("Falhas"),
      ignorados: z.string().default("Ignorados"),
      conferencia: z.string().default("Em conferência"),
      percentualDe: z.string().default("{percentual}% do total"),
      rotulo: z.string().default("Funil da campanha"),
    }).default({}),
    grafico: z.object({
      titulo: z.string().default("Enfileiradas por dia"),
      enfileiradas: z.string().default("Enfileiradas"),
      limite: z.string().default("Limite diário"),
      vazio: z.string().default("Ainda não saiu nenhuma mensagem."),
      rotulo: z.string().default("Gráfico de mensagens enfileiradas por dia comparadas ao limite diário"),
    }).default({}),
    limite: z.object({
      titulo: z.string().default("Limite diário"),
      hoje: z.string().default("Vale hoje: {limite}"),
      efeito: z.string().default("A mudança vale no próximo ciclo de envio, nunca passa do teto da instância ({teto}) e não apaga o que já saiu hoje."),
      campo: z.string().default("Novo limite diário"),
      ritmo: z.string().default("Mensagens por minuto"),
      salvar: z.string().default("Salvar limite"),
      salvando: z.string().default("Salvando..."),
      salvo: z.string().default("Limite atualizado."),
      erro: z.string().default("Não foi possível alterar o limite."),
      invalido: z.string().default("Informe um número entre 1 e {teto}."),
      instanciaHoje: z.string().default("Hoje, na instância: {enviadas} de {teto}"),
      somenteAdministrador: z.string().default("Só o administrador altera o limite."),
    }).default({}),
    alertaPausa: z.object({
      titulo: z.string().default("Esta campanha foi pausada automaticamente"),
      motivo: z.string().default("Motivo: {motivo}"),
      quando: z.string().default("Pausada em {data}"),
      oQueFazer: z.string().default("O que fazer"),
      passo1: z.string().default("Confira na aba Destinatários os códigos de erro e os motivos das falhas."),
      passo2: z.string().default("Resolva a causa: template, qualidade do número ou limite da Meta."),
      passo3: z.string().default("Quando estiver resolvido, retome a campanha. Se o problema continuar, ela pausa de novo."),
    }).default({}),
    destinatarios: z.object({
      filtroStatus: z.string().default("Status"),
      filtroMotivo: z.string().default("Motivo"),
      todos: z.string().default("Todos"),
      todosMotivos: z.string().default("Todos os motivos"),
      vazio: z.string().default("Nenhum destinatário com estes filtros."),
      carregando: z.string().default("Carregando destinatários"),
      erro: z.string().default("Não foi possível carregar os destinatários."),
      exportar: z.string().default("Exportar CSV"),
      exportando: z.string().default("Exportando..."),
      erroExportar: z.string().default("Não foi possível exportar o CSV."),
      colunas: z.object({
        contato: z.string().default("Contato"),
        telefone: z.string().default("Telefone"),
        status: z.string().default("Status"),
        motivo: z.string().default("Motivo"),
        erro: z.string().default("Código de erro"),
        enviado: z.string().default("Enviado"),
        entregue: z.string().default("Entregue"),
        lido: z.string().default("Lido"),
        respondeu: z.string().default("Respondeu"),
      }).default({}),
      semData: z.string().default("-"),
      total: z.string().default("{total} destinatário(s)"),
    }).default({}),
    conferencia: z.object({
      titulo: z.string().default("Conferência manual"),
      descricao: z.string().default("Envios cujo resultado não se sabe. Nunca são reenviados sozinhos: confira no provedor o que aconteceu e marque como conferido."),
      vazio: z.string().default("Nada para conferir."),
      marcar: z.string().default("Marcar como conferido"),
      marcando: z.string().default("Marcando..."),
      erro: z.string().default("Não foi possível marcar como conferido."),
      carregando: z.string().default("Carregando conferência"),
      erroCarregar: z.string().default("Não foi possível carregar a conferência."),
      somenteAdministrador: z.string().default("Só o administrador marca como conferido."),
    }).default({}),
  }).default({}),
  configuracaoDaInstancia: z.object({
    titulo: z.string().default("Configurações de campanhas"),
    descricao: z.string().default("Limites e pausa automática desta instância. O que mudar vale no próximo ciclo, sem deploy."),
    carregando: z.string().default("Carregando configurações"),
    erro: z.string().default("Não foi possível carregar as configurações."),
    envioHabilitado: z.string().default("Envio de campanhas habilitado"),
    envioHabilitadoAjuda: z.string().default("Interruptor geral. Desligado, nenhuma campanha envia."),
    teto: z.string().default("Teto diário da instância"),
    tetoAjuda: z.string().default("Máximo de mensagens por dia somando todas as campanhas."),
    limitePadrao: z.string().default("Limite diário padrão de uma campanha"),
    limiteMeta: z.string().default("Limite da Meta (informado)"),
    limiteMetaAjuda: z.string().default("Contatos únicos por 24h que a Meta concede ao seu número. 0 = não informado. O CRM ainda não lê esse valor da Meta."),
    pausaTitulo: z.string().default("Pausa automática"),
    pausaDescricao: z.string().default("A campanha pausa sozinha quando a taxa de falha passa do limiar, ou quando a Meta devolve um código de bloqueio."),
    limiarFalha: z.string().default("Limiar de falha (%)"),
    janelaDeEnvios: z.string().default("Últimos envios considerados"),
    minimoAmostra: z.string().default("Mínimo de envios para avaliar"),
    valorInvalido: z.string().default("Valor fora da faixa permitida."),
    salvar: z.string().default("Salvar configurações"),
    salvando: z.string().default("Salvando..."),
    salvo: z.string().default("Configurações salvas."),
    erroSalvar: z.string().default("Não foi possível salvar. Confira os valores."),
    somenteAdministrador: z.string().default("Só o administrador altera estas configurações. Você pode consultar os valores."),
    prazos: z.string().default("Prazos fixos"),
    conferenciaApos: z.string().default("Enfileirado sem confirmação vai para conferência após {minutos} min."),
    respondeuJanela: z.string().default("Resposta conta como da campanha por até {dias} dia(s)."),
  }).default({}),
});

export type CampanhasTextos = z.infer<typeof CampanhasTextosSchema>;
