package com.synapse.crm.app.equipe;
import static com.synapse.crm.app.seguranca.ApoioAutenticacao.*;
import static org.assertj.core.api.Assertions.assertThat;

import java.util.Map;
import java.util.UUID;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;

import com.synapse.crm.app.PostgresIT;
import com.synapse.crm.app.seguranca.ApoioAutenticacao;
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)@ActiveProfiles("dev")@TestPropertySource(properties="synapse.seguranca.token-interno=segredo-equipe-e13")class EquipeEPresencaIT extends PostgresIT{
 @Autowired TestRestTemplate http;@Autowired JdbcTemplate jdbc;JsonSemChecked json=new JsonSemChecked();
 @Test @DisplayName("gestor cria, edita e desativa sem deletar usuario")void crud()throws Exception{String sufixo=UUID.randomUUID().toString().substring(0,8);var criada=chamar(EMAIL_GESTOR,SENHA_GESTOR,HttpMethod.POST,"/api/v1/usuarios",Map.of("nome","Atendente E13","email","e13-"+sufixo+"@teste.local","senha","senha-e13-segura","papel","ATENDENTE"));assertThat(criada.getStatusCode()).isEqualTo(HttpStatus.CREATED);UUID id=UUID.fromString(json.readTree(criada.getBody()).path("id").asText());assertThat(jdbc.queryForObject("SELECT senha_hash FROM usuario WHERE id=?",String.class,id)).doesNotContain("senha-e13-segura");var editada=chamar(EMAIL_GESTOR,SENHA_GESTOR,HttpMethod.PUT,"/api/v1/usuarios/"+id,Map.of("nome","Subgestora E13","email","sub-"+sufixo+"@teste.local","papel","SUBGESTOR"));assertThat(editada.getBody()).contains("Subgestora E13").contains("SUBGESTOR");assertThat(chamar(EMAIL_GESTOR,SENHA_GESTOR,HttpMethod.PATCH,"/api/v1/usuarios/"+id+"/desativar",null).getStatusCode()).isEqualTo(HttpStatus.NO_CONTENT);assertThat(jdbc.queryForObject("SELECT count(*) FROM usuario WHERE id=?",Integer.class,id)).isOne();assertThat(jdbc.queryForObject("SELECT ativo FROM usuario WHERE id=?",Boolean.class,id)).isFalse();}
 @Test @DisplayName("criar usuario com senha abaixo da politica configurada e recusado com a regra na mensagem")void criarComSenhaForaDaPolitica(){var resposta=chamar(EMAIL_GESTOR,SENHA_GESTOR,HttpMethod.POST,"/api/v1/usuarios",Map.of("nome","Invasor E31b","email","e31b-"+UUID.randomUUID()+"@teste.local","senha","curta","papel","ATENDENTE"));assertThat(resposta.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);assertThat(resposta.getBody()).contains("8");}
 @Test @DisplayName("atendente nao cria, edita nem desativa membros da equipe")void negativoGestao(){UUID bruno=jdbc.queryForObject("SELECT id FROM usuario WHERE email=?",UUID.class,EMAIL_BRUNO);assertThat(chamar(EMAIL_ANA,SENHA_ATENDENTE,HttpMethod.POST,"/api/v1/usuarios",Map.of("nome","Invasor","email","invasor@teste.local","senha","senha-invasor","papel","ATENDENTE")).getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);assertThat(chamar(EMAIL_ANA,SENHA_ATENDENTE,HttpMethod.PUT,"/api/v1/usuarios/"+bruno,Map.of("nome","Alterado","email",EMAIL_BRUNO,"papel","SUBGESTOR")).getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);assertThat(chamar(EMAIL_ANA,SENHA_ATENDENTE,HttpMethod.PATCH,"/api/v1/usuarios/"+bruno+"/desativar",null).getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);assertThat(jdbc.queryForObject("SELECT nome FROM usuario WHERE id=?",String.class,bruno)).isEqualTo("Bruno Atendente");}
 @Test @DisplayName("presenca online nao liga disponibilidade da IA e offline continua fora")void presencaNaoAlimentaIa(){UUID ana=jdbc.queryForObject("SELECT id FROM usuario WHERE email=?",UUID.class,EMAIL_ANA);jdbc.update("DELETE FROM disponibilidade_atendente_ia WHERE atendente_id=?",ana);assertThat(chamar(EMAIL_ANA,SENHA_ATENDENTE,HttpMethod.PATCH,"/api/v1/usuarios/me/presenca",Map.of("status","ONLINE")).getBody()).contains("ONLINE");assertThat(interno()).doesNotContain(ana.toString());chamar(EMAIL_GESTOR,SENHA_GESTOR,HttpMethod.PATCH,"/api/v1/usuarios/"+ana+"/disponibilidade-ia",Map.of("disponivelParaIa",true));assertThat(interno()).contains(ana.toString()).contains("Ana Atendente");chamar(EMAIL_ANA,SENHA_ATENDENTE,HttpMethod.PATCH,"/api/v1/usuarios/me/presenca",Map.of("status","OFFLINE"));assertThat(interno()).doesNotContain(ana.toString());}
 @Test @DisplayName("backfill liga atendentes ativos e preserva inativos fora do rodizio")void backfillAtendentesAtivos(){UUID inativo=UUID.randomUUID();String hash=jdbc.queryForObject("SELECT senha_hash FROM usuario WHERE email=?",String.class,EMAIL_ANA);jdbc.update("INSERT INTO usuario(id,nome,email,senha_hash,papel,ativo,status_presenca) VALUES(?,?,?,?,'ATENDENTE',FALSE,'OFFLINE')",inativo,"Atendente Inativo E36b",inativo+"@teste.local",hash);jdbc.update("INSERT INTO disponibilidade_atendente_ia(atendente_id,disponivel_para_ia) VALUES(?,FALSE)",inativo);jdbc.update("UPDATE disponibilidade_atendente_ia SET disponivel_para_ia=FALSE");String backfill="INSERT INTO disponibilidade_atendente_ia (atendente_id, disponivel_para_ia) SELECT id, TRUE FROM usuario WHERE ativo=TRUE AND papel='ATENDENTE' ON CONFLICT (atendente_id) DO UPDATE SET disponivel_para_ia=TRUE, atualizado_em=now()";jdbc.update(backfill);jdbc.update(backfill);Integer ativos=jdbc.queryForObject("SELECT count(*) FROM usuario WHERE ativo=TRUE AND papel='ATENDENTE'",Integer.class);Integer ligados=jdbc.queryForObject("SELECT count(*) FROM disponibilidade_atendente_ia d JOIN usuario u ON u.id=d.atendente_id WHERE u.ativo=TRUE AND u.papel='ATENDENTE' AND d.disponivel_para_ia=TRUE",Integer.class);assertThat(ativos).isEqualTo(ligados);assertThat(interno()).doesNotContain(inativo.toString());assertThat(jdbc.queryForObject("SELECT disponivel_para_ia FROM disponibilidade_atendente_ia WHERE atendente_id=?",Boolean.class,inativo)).isFalse();}
 @Test @DisplayName("criar atendente cria disponibilidade IA e promover papel preserva linha")void defaultsDeDisponibilidadeNaCriacaoEPapel(){String sufixo=UUID.randomUUID().toString().substring(0,8);String email="default-"+sufixo+"@teste.local";var atendente=chamar(EMAIL_GESTOR,SENHA_GESTOR,HttpMethod.POST,"/api/v1/usuarios",Map.of("nome","Atendente Default","email",email,"senha","senha-default-segura","papel","ATENDENTE"));assertThat(atendente.getStatusCode()).isEqualTo(HttpStatus.CREATED);UUID id=UUID.fromString(json.readTree(atendente.getBody()).path("id").asText());assertThat(jdbc.queryForObject("SELECT disponivel_para_ia FROM disponibilidade_atendente_ia WHERE atendente_id=?",Boolean.class,id)).isTrue();assertThat(chamar(EMAIL_GESTOR,SENHA_GESTOR,HttpMethod.POST,"/api/v1/usuarios",Map.of("nome","Subgestor Sem IA","email","sub-"+sufixo+"@teste.local","senha","senha-sub-segura","papel","SUBGESTOR")).getStatusCode()).isEqualTo(HttpStatus.CREATED);UUID sub=jdbc.queryForObject("SELECT id FROM usuario WHERE email=?",UUID.class,"sub-"+sufixo+"@teste.local");assertThat(jdbc.queryForObject("SELECT count(*) FROM disponibilidade_atendente_ia WHERE atendente_id=?",Integer.class,sub)).isZero();assertThat(chamar(EMAIL_GESTOR,SENHA_GESTOR,HttpMethod.PUT,"/api/v1/usuarios/"+id,Map.of("nome","Promovido","email",email,"papel","SUBGESTOR")).getStatusCode()).isEqualTo(HttpStatus.OK);assertThat(chamar(EMAIL_GESTOR,SENHA_GESTOR,HttpMethod.PUT,"/api/v1/usuarios/"+id,Map.of("nome","Voltou","email",email,"papel","ATENDENTE")).getStatusCode()).isEqualTo(HttpStatus.OK);assertThat(jdbc.queryForObject("SELECT disponivel_para_ia FROM disponibilidade_atendente_ia WHERE atendente_id=?",Boolean.class,id)).isTrue();assertThat(chamar(EMAIL_GESTOR,SENHA_GESTOR,HttpMethod.PATCH,"/api/v1/usuarios/"+id+"/desativar",null).getStatusCode()).isEqualTo(HttpStatus.NO_CONTENT);assertThat(jdbc.queryForObject("SELECT disponivel_para_ia FROM disponibilidade_atendente_ia WHERE atendente_id=?",Boolean.class,id)).isFalse();}
 @Test @DisplayName("GET /api/v1/me devolve nome, papel e presenca de quem chamou, mesmo sendo atendente")void meuUsuario(){var resposta=chamar(EMAIL_ANA,SENHA_ATENDENTE,HttpMethod.GET,"/api/v1/me",null);assertThat(resposta.getStatusCode()).isEqualTo(HttpStatus.OK);assertThat(resposta.getBody()).contains("\"nome\":\"Ana Atendente\"").contains("\"papel\":\"ATENDENTE\"").contains("\"presenca\"");}
 @Test @DisplayName("PATCH /api/v1/me altera apenas o nome do proprio usuario e preserva papel e email")void meuPerfil(){UUID ana=jdbc.queryForObject("SELECT id FROM usuario WHERE email=?",UUID.class,EMAIL_ANA);UUID bruno=jdbc.queryForObject("SELECT id FROM usuario WHERE email=?",UUID.class,EMAIL_BRUNO);try{var resposta=chamar(EMAIL_ANA,SENHA_ATENDENTE,HttpMethod.PATCH,"/api/v1/me",Map.of("nome","Ana Perfil E49"));assertThat(resposta.getStatusCode()).isEqualTo(HttpStatus.OK);assertThat(resposta.getBody()).contains("Ana Perfil E49").contains("ATENDENTE").contains(EMAIL_ANA);assertThat(jdbc.queryForObject("SELECT nome FROM usuario WHERE id=?",String.class,ana)).isEqualTo("Ana Perfil E49");assertThat(jdbc.queryForObject("SELECT nome FROM usuario WHERE id=?",String.class,bruno)).isEqualTo("Bruno Atendente");assertThat(jdbc.queryForObject("SELECT papel::text FROM usuario WHERE id=?",String.class,ana)).isEqualTo("ATENDENTE");}finally{jdbc.update("UPDATE usuario SET nome='Ana Atendente' WHERE id=?",ana);}}
 @Test @DisplayName("GET /api/v1/me sem token devolve 401")void meuUsuarioSemToken(){assertThat(http.exchange("/api/v1/me",HttpMethod.GET,HttpEntity.EMPTY,String.class).getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);}
 @Test @DisplayName("mini-dashboard agrega avaliacoes reais")void avaliacoes(){UUID ana=jdbc.queryForObject("SELECT id FROM usuario WHERE email=?",UUID.class,EMAIL_ANA);UUID canal=jdbc.queryForObject("SELECT id FROM canal ORDER BY nome LIMIT 1",UUID.class);UUID lead=UUID.randomUUID(),atendimento=UUID.randomUUID();jdbc.update("INSERT INTO lead(id,nome,atendente_responsavel_id,status_basico) VALUES(?,?,?,'EM_ATENDIMENTO')",lead,"Avaliacao E13 "+lead,ana);jdbc.update("INSERT INTO atendimento(id,lead_id,canal_id,atendente_id,status) VALUES(?,?,?,?,'EM_ATENDIMENTO')",atendimento,lead,canal,ana);jdbc.update("INSERT INTO avaliacao(id,atendimento_id,atendente_id,nota) VALUES(?,?,?,5)",UUID.randomUUID(),atendimento,ana);String corpo=chamar(EMAIL_GESTOR,SENHA_GESTOR,HttpMethod.GET,"/api/v1/equipe/avaliacoes",null).getBody();assertThat(corpo).contains("\"mediaGeral\":5.00").contains("Ana Atendente").contains("\"total\":1");}
 static class JsonSemChecked{com.fasterxml.jackson.databind.JsonNode readTree(String valor){try{return new ObjectMapper().readTree(valor);}catch(Exception e){throw new AssertionError(e);}}}
 String interno(){HttpHeaders h=new HttpHeaders();h.set("X-Synapse-Token","segredo-equipe-e13");return http.exchange("/internal/v1/atendentes/disponiveis",HttpMethod.GET,new HttpEntity<>(h),String.class).getBody();}
 ResponseEntity<String> chamar(String e,String s,HttpMethod m,String u,Object c){String token=ApoioAutenticacao.login(http,e,s).accessToken();HttpHeaders h=new HttpHeaders();h.setBearerAuth(token);h.setContentType(MediaType.APPLICATION_JSON);return http.exchange(u,m,new HttpEntity<>(c,h),String.class);}}
